version: '3.3'

services:
  db:
    env_file:
      - .env
    container_name: django_db
    image: postgres
    volumes:
      - /home/django_db:/home/Documents:rw
  
  web:
    build: .
    image: django
    container_name: django_drf
    env_file:
      - .env
    volumes:
      - .:/code/django_drf
    depends_on:
      - db
    ports:
      - "8866:8866"
  redis:
    container_name: redis
    image: redis:5.0.5
    hostname: redis
  celery:
    restart: always
    build:
      context: .
    command: celery -A core worker --loglevel=INFO
    volumes:
      - ./home/celery:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - web