version: '3.3'

services:
  db:
    env_file:
      - .env
    container_name: django_db
    image: postgres
    volumes:
      - /home/django_db:/var/lib/postgresql/data:rw
  web:
    build: .
    image: django
    container_name: django_drf
    env_file:
      - .env
    volumes:
      - /home/django_drf:/code
    depends_on:
      - db
    ports:
      - "8866:8866"
  redis:
    image: redis:alpine
    ports:
      - "7055:6379"
    container_name: redis
    restart: unless-stopped
  celery:
    restart: always
    build:
      context: .
    command: celery -A core worker --loglevel=INFO & celery -A core beat --loglevel=INFO
    volumes:
      - /home/celery:/code
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - web