# Generated by Django 4.2.4 on 2023-08-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Borsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=5)),
                ('buying', models.IntegerField()),
                ('buyingstr', models.CharField(max_length=50)),
                ('selling', models.IntegerField()),
                ('sellingstr', models.CharField(max_length=50)),
                ('rate', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('date', models.DateTimeField()),
                ('datetime', models.DateTimeField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Borsa',
                'verbose_name_plural': "Borsa'",
                'db_table': 'borsa',
            },
        ),
    ]
