# Generated by Django 4.2.4 on 2023-08-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_borsa_date_alter_borsa_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borsa',
            name='datetime',
            field=models.CharField(max_length=50),
        ),
    ]
