# Generated by Django 4.2.4 on 2023-08-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_coin_delete_borsa'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='calculated',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
